import mapUrl from "../../assets/maps/MountainTrack.glb?url";
import { loadMap, buildMapTrack } from "./glb-map.js";

// ---------------------------------------------------------------------
// OFFICIAL MAP 2 — Mountain Track
//
// A hill climb and descent round a mountain, modelled in Blender
// (assets/maps/MountainTrack.glb, generated by blender/mountain/
// mountain_track.py). 1.48 km, 12 m of road, climbing from 8 m to 83 m,
// through a closed tunnel at the summit and back down over a viaduct.
// Every corner is a left-hander and every one leans the right way: the
// outside edge is up, from about 2 degrees on the straights to 13 in the
// two tight corners (R19 after the start, R15 at 1.33 km). Nothing leans
// the wrong way.
//
// Unlike the other two maps this one has real barriers: continuous
// guardrails on both sides, 6.3 m from the centre and 0.15-0.8 m high,
// which collide as their own mesh — so no soft wall. The tunnel walls
// collide the same way. The terrain is scenery only: the rails keep
// every car on the road, and a 45 000-triangle mountain would be a lot
// of collision geometry for nobody to touch.
//
// The start line (road sample 0) sits on a flat straight with nothing
// tighter than R30 for 60 m either way, so the grid lines up on level
// ground and gets going before the first corner.
//
// Mesh names are as three.js sanitises them: spaces become underscores.
// ---------------------------------------------------------------------

buildMountain.preload = () => loadMap(mapUrl);

// `gltf` is what preload() resolved to — loadLevel in main.js awaits it.
export function buildMountain(RAPIER, world, scene, gltf) {
  const map = buildMapTrack(RAPIER, world, scene, gltf, {
    name: "MountainTrack",
    roadName: "Mountain_Race_Track",
    surfaces: [
      { match: /^Mountain_Race_Track$/, friction: 1.0 },
      // Asphalt between the road edge and the rails, on the same plane
      { match: /^Road_Shoulder_(Left|Right)$/, friction: 1.0 },
    ],
    walls: /^(Guardrail_(Left|Right)|Tunnel_Wall)$/,
    decals: /^(White_Edge|Yellow_Centre|Race_Direction_Arrow|Start_Finish_Checker|Red_White_Curb)/,
    minimap: /^(Mountain_Race_Track|White_Edge|Guardrail_(Left|Right)$)/,
    // The rails are the boundary, as on a generated track, and wallLimit
    // is where they stand. A soft wall here fought the rails: where the
    // centreline and the modelled road disagree by even half a metre, it
    // held cars short of a rail they could see and they stalled there.
    softWalls: false,
    wallLimit: 6.2,
    // Light smoothing only: the ribbon is evenly sampled (1.84 m) and
    // smooth, and the default (6 m, 3 passes) would pull the line off the
    // modelled road in the two tight corners.
    centreline: { spacing: 3, passes: 1 },
    track: { checkpointSpacing: 120 },
  });
  const { track } = map;

  const gate = track.spawnAt(0);
  return {
    // Falling rocks where there is a real slope above the road (measured:
    // the ground 25 m to one side is 25-50 m above it). Not in the tunnel
    // (683-821 m), not on the viaduct (1,018-1,160 m), not on the downhill
    // face (about 340-1,000 m, where the ground falls away), and clear of
    // the start line. The uphill side is found from the terrain.
    rockfall: {
      zones: [
        { s0: 190, s1: 290 },
        { s0: 1180, s1: 1290 },
        { s0: 1320, s1: 1420 },
      ],
      ground: map.group.children.filter((m) => /Grass|Mountain Rock|Rock Highlight/.test(m.name)),
      signOffset: 7.4, // just beyond the rail
    },
    name: "mountain",
    index: 2,
    title: "Mountain Track",
    track,
    // Solo: the mountain is you against the road. Only the Grand Prix is
    // a race against other cars.
    opponents: 0,
    pickups: { repair: 4, boost: 5 },
    spawn: gate.position,
    quaternion: gate.quaternion,
    lit: { sun: [70, 110, 40], fog: [0xa7bccb, 260, 1000], sky: 0xa7bccb },
    dispose: map.dispose,
  };
}
