import * as THREE from "three";
import mapUrl from "../../assets/maps/MountainTrack.glb?url";
import { loadMap, buildMapTrack } from "./glb-map.js";
import { MountainScenery, loadMountainProps } from "./mountain-scenery.js";

// ---------------------------------------------------------------------
// OFFICIAL MAP 2 — Mountain Track
//
// A hill climb and descent round a mountain, modelled in Blender
// (assets/maps/MountainTrack.glb, generated by blender/mountain/
// mountain_track.py). 1.48 km, 12 m of road, climbing from 8 m to 83 m,
// through a closed tunnel at the summit and back down over a viaduct.
// Every corner is a left-hander and every one leans the right way: the
// outside edge is up, from about 2 degrees on the straights to 13 in the
// two tight corners (R19 after the start, R15 at 1.33 km). Nothing leans
// the wrong way.
//
// Unlike the other two maps this one has real barriers: continuous
// guardrails on both sides, 6.3 m from the centre and 0.15-0.8 m high,
// which collide as their own mesh — so no soft wall. The tunnel walls
// collide the same way. The terrain is scenery only: the rails keep
// every car on the road, and a 45 000-triangle mountain would be a lot
// of collision geometry for nobody to touch.
//
// The start line (road sample 0) sits on a flat straight with nothing
// tighter than R30 for 60 m either way, so the grid lines up on level
// ground and gets going before the first corner.
//
// Mesh names are as three.js sanitises them: spaces become underscores.
// ---------------------------------------------------------------------

buildMountain.preload = async () => {
  const [map] = await Promise.all([loadMap(mapUrl), loadMountainProps()]);
  return map;
};

// ---------------------------------------------------------------------
// The refined look, applied to the map's own materials by name (the same
// palette as the refined City Track: blue-charcoal asphalt, limestone
// concrete, coral accents, softer greens and warm-grey rock). The values
// are Blender's linear RGB, so they are set as linear. Geometry is
// untouched, so the road, rails and colliders are exactly as before.
// ---------------------------------------------------------------------
const REFINED = {
  "Fresh Dark Asphalt": [0.085, 0.105, 0.118],
  "Asphalt Shoulder": [0.15, 0.17, 0.18],
  "White Road Marking": [0.92, 0.92, 0.9],
  "Racing Red": [0.78, 0.19, 0.14], // kerb and gantry: coral
  "Curb White": [0.76, 0.76, 0.69],
  "Grass Dark": [0.1, 0.22, 0.15],
  "Grass Mid": [0.13, 0.27, 0.18],
  "Grass Light": [0.23, 0.39, 0.25],
  "Mountain Rock": [0.3, 0.29, 0.28],
  "Rock Highlight": [0.5, 0.46, 0.4],
  "Tunnel Concrete": [0.63, 0.64, 0.58],
  "Tunnel Interior": [0.2, 0.22, 0.23],
  "Bridge Concrete": [0.68, 0.7, 0.64],
  "Pine Green": [0.05, 0.2, 0.09],
  "Pine Dark": [0.03, 0.12, 0.05],
  "Tree Bark": [0.18, 0.07, 0.025],
};

// ---------------------------------------------------------------------
// Rock walls: the map's flat-coloured rock faces get a world-space
// triplanar rock texture, horizontal strata that follow height, darker
// cracks, and snow lying on the upward-facing faces near the summit. The
// facets stay flat-shaded (the face normal comes from screen derivatives).
// Geometry is untouched.
// ---------------------------------------------------------------------
function rockTexture() {
  const c = document.createElement("canvas");
  c.width = c.height = 256;
  const g = c.getContext("2d");
  let a = 4242;
  const r = () => ((a = (Math.imul(a, 1664525) + 1013904223) >>> 0) / 4294967296);
  g.fillStyle = "#8a8782";
  g.fillRect(0, 0, 256, 256);
  for (let i = 0; i < 700; i++) {
    const x = r() * 256, y = r() * 256, w = 6 + r() * 34, h = 3 + r() * 14;
    const v = 90 + Math.floor(r() * 110);
    g.fillStyle = `rgba(${v},${v - 3},${v - 8},.35)`;
    for (const [dx, dy] of [[0, 0], [256, 0], [-256, 0], [0, 256], [0, -256]]) g.fillRect(x + dx, y + dy, w, h);
  }
  g.strokeStyle = "rgba(25,22,20,.55)";
  for (let i = 0; i < 70; i++) {
    let x = r() * 256, y = r() * 256;
    g.lineWidth = 0.6 + r() * 1.2;
    g.beginPath();
    g.moveTo(x, y);
    for (let k = 0; k < 6; k++) { x += (r() - 0.5) * 26; y += (r() - 0.35) * 22; g.lineTo(x, y); }
    g.stroke();
  }
  const t = new THREE.CanvasTexture(c);
  t.wrapS = t.wrapT = THREE.RepeatWrapping;
  t.colorSpace = THREE.SRGBColorSpace;
  t.anisotropy = 4;
  return t;
}

function rockify(group, tex) {
  const done = new Set();
  group.traverse((o) => {
    if (!o.isMesh) return;
    for (const m of Array.isArray(o.material) ? o.material : [o.material]) {
      if (!m || done.has(m) || !/^(Mountain Rock|Rock Highlight)$/.test(m.name) || m.userData.rockified) continue;
      done.add(m);
      m.userData.rockified = true;
      m.onBeforeCompile = (shader) => {
        shader.uniforms.uRock = { value: tex };
        shader.vertexShader = shader.vertexShader
          .replace("#include <common>", "#include <common>\nvarying vec3 vWP;")
          .replace("#include <begin_vertex>", "#include <begin_vertex>\nvWP = (modelMatrix * vec4(transformed, 1.0)).xyz;");
        shader.fragmentShader = shader.fragmentShader
          .replace("#include <common>", "#include <common>\nvarying vec3 vWP;\nuniform sampler2D uRock;")
          .replace(
            "#include <map_fragment>",
            `#include <map_fragment>
            vec3 fn = normalize(cross(dFdx(vWP), dFdy(vWP)));
            vec3 w = pow(abs(fn), vec3(4.0)); w /= (w.x + w.y + w.z);
            vec3 tx = texture2D(uRock, vWP.yz * 0.11).rgb * w.x
                    + texture2D(uRock, vWP.xz * 0.11).rgb * w.y
                    + texture2D(uRock, vWP.xy * 0.11).rgb * w.z;
            vec3 big = texture2D(uRock, vWP.xz * 0.013 + vWP.y * 0.004).rgb;
            // strata: bands that follow height, warped by the big noise
            float band = sin(vWP.y * 0.85 + big.r * 5.0) * 0.5 + 0.5;
            vec3 rock = diffuseColor.rgb * (0.55 + 0.9 * tx) * mix(0.78, 1.18, band);
            rock = mix(rock, rock * vec3(1.12, 0.98, 0.84), smoothstep(0.55, 1.0, band) * 0.5);
            // snow settles on upward faces near the top
            float snowLine = 56.0 + big.g * 14.0;
            float snow = smoothstep(0.45, 0.8, fn.y) * smoothstep(snowLine, snowLine + 8.0, vWP.y);
            diffuseColor.rgb = mix(rock, vec3(0.93, 0.95, 0.98), snow);`
          );
      };
      m.customProgramCacheKey = () => "rockify";
      m.needsUpdate = true;
    }
  });
}

function applyRefinedLook(group) {
  const seen = new Set(); // materials are shared between meshes
  group.traverse((o) => {
    if (!o.isMesh) return;
    for (const m of Array.isArray(o.material) ? o.material : [o.material]) {
      const c = m && REFINED[m.name];
      if (!c || seen.has(m)) continue;
      seen.add(m);
      m.color.setRGB(c[0], c[1], c[2], THREE.LinearSRGBColorSpace);
    }
  });
}

// `gltf` is what preload() resolved to — loadLevel in main.js awaits it.
export function buildMountain(RAPIER, world, scene, gltf) {
  const map = buildMapTrack(RAPIER, world, scene, gltf, {
    name: "MountainTrack",
    roadName: "Mountain_Race_Track",
    surfaces: [
      { match: /^Mountain_Race_Track$/, friction: 1.0 },
      // Asphalt between the road edge and the rails, on the same plane
      { match: /^Road_Shoulder_(Left|Right)$/, friction: 1.0 },
    ],
    walls: /^(Guardrail_(Left|Right)|Tunnel_Wall)$/,
    decals: /^(White_Edge|Yellow_Centre|Race_Direction_Arrow|Start_Finish_Checker|Red_White_Curb)/,
    minimap: /^(Mountain_Race_Track|White_Edge|Guardrail_(Left|Right)$)/,
    // The rails are the boundary, as on a generated track, and wallLimit
    // is where they stand. A soft wall here fought the rails: where the
    // centreline and the modelled road disagree by even half a metre, it
    // held cars short of a rail they could see and they stalled there.
    softWalls: false,
    wallLimit: 6.2,
    // Light smoothing only: the ribbon is evenly sampled (1.84 m) and
    // smooth, and the default (6 m, 3 passes) would pull the line off the
    // modelled road in the two tight corners.
    centreline: { spacing: 3, passes: 1 },
    track: { checkpointSpacing: 120 },
  });
  const { track } = map;
  applyRefinedLook(map.group);
  rockify(map.group, rockTexture());
  const scenery = new MountainScenery(scene, track, map.group.children.filter((m) => /Grass|Mountain Rock|Rock Highlight/.test(m.name)), { tunnel: [683, 821] });

  const gate = track.spawnAt(0);
  return {
    // Falling rocks where there is a real slope above the road (measured:
    // the ground 25 m to one side is 25-50 m above it). Not in the tunnel
    // (683-821 m), not on the viaduct (1,018-1,160 m), not on the downhill
    // face (about 340-1,000 m, where the ground falls away), and clear of
    // the start line. The uphill side is found from the terrain.
    rockfall: {
      zones: [
        { s0: 190, s1: 290 },
        { s0: 1180, s1: 1290 },
        { s0: 1320, s1: 1420 },
      ],
      ground: map.group.children.filter((m) => /Grass|Mountain Rock|Rock Highlight/.test(m.name)),
      signOffset: 7.4, // just beyond the rail
    },
    // The viaduct (1,018-1,160 m) is the one stretch with nothing beside
    // the road at all — no slope to drop rocks, no rail-height drop-off,
    // just open air over the gorge. A crosswind belongs there and
    // nowhere else on this lap. 5200 N, not 4200: on a 1200 kg car that's
    // ~4.3 m/s^2 at full strength — comfortably below boostForce (6500 N)
    // but enough to actually need countersteer, not just a push too
    // gentle for the tyres' own grip to shrug off unnoticed.
    crosswind: [{ s0: 1018, s1: 1160, side: 1, force: 5200, signOffset: 7.4 }],
    // Low ground mist, not summit cloud, filling the whole gap between the
    // last rockfall zone and the line. That zone is the 1180-1290 one, not
    // the 1320-1420 entry above: Rockfall's own uphill-slope check
    // (measured from the terrain, not configured) finds no real slope
    // over that last stretch and drops it silently — so it never arms,
    // never signs, never drops a rock, and 1320-1420 is actually just more
    // plain road. The real gap to the line is 1290-1474.7, not 1420-1474.7.
    // A short 10 m ramp (see FogPatch's `ramp` option, default 40) so it
    // reads as present almost the instant the rocks stop, not a 40 m fade
    // that is still near-baseline visibility for the first several
    // seconds. Full strength holds for the next 160 m, nearly the whole
    // remaining stretch, clearing only in the last 15 m before the line —
    // there to be driven through right up to the flag, not resolved with
    // a big empty buffer beforehand, but still gone before the line
    // itself so it never reads as lingering past it. Denser than the
    // default near/far too (12/80, not 20/140): the default read as too
    // faint to notice at a glance.
    fogPatch: [{ s0: 1300, s1: 1460, ramp: 10, near: 12, far: 80, signOffset: 7.4 }],
    name: "mountain",
    index: 2,
    title: "Mountain Track",
    track,
    // Solo: the mountain is you against the road. Only the Grand Prix is
    // a race against other cars.
    opponents: 0,
    // One lap up, through the tunnel, and back down to the line before
    // the clock runs out. Boost orbs buy you more of it rather than
    // filling the boost meter — the climb is the opponent here.
    pickups: { repair: 4, boost: 5, boostSeconds: 10 },
    // 90 s: this 1.48 km lap climbs, threads a tunnel, a crosswind and a
    // fog patch right before the line, and descends again — needs ~59
    // km/h average, slower than the City by nature, but still tight
    // enough that actually handling the hazards (not just surviving
    // them) is what gets you home in time.
    race: { laps: 1, timeLimit: 90 },
    spawn: gate.position,
    quaternion: gate.quaternion,
    // Late-afternoon light, as on the refined City Track: low warm sun, a
    // dusk sky, and a haze that suits the climb.
    lit: {
      sun: [-80, 46, 55],
      sunColor: 0xffcf9e,
      sunIntensity: 2.6,
      hemi: [0x9db6d6, 0x4b4038, 1.6],
      sky: { top: 0x3a5f94, horizon: 0xf0b88a, bottom: 0x4a423c },
      fog: [0xd2b79f, 200, 950],
      exposure: 1.0,
    },
    update: (t) => scenery.update(t),
    scenery,
    dispose: () => {
      scenery.dispose();
      map.dispose();
    },
  };
}
